views/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from models.original import Original
from models.contact import Contact
from flask import session, flash
from models.user import requires_login

contact_blueprint = Blueprint("contacts", __name__)


@contact_blueprint.route("/")
@requires_login
def index():
    contacts = Contact.find_many_by('user_email', session['email'])
    return render_template("contacts/index.html", contacts=contacts)


@contact_blueprint.route("/new", methods=['GET', 'POST'])
@requires_login
def new_contact():
    if request.method == "POST":
        # Populate the Data
        name_first = request.form["name_first"]
        name_last = request.form["name_last"]
        phone = request.form["phone"]
        email = request.form["email"]
        address = request.form["address"]
        user_email = session['email']

        # Initialize Object and save to database
        Contact(name_first,
                name_last,
                phone,
                email,
                address,
                user_email).save_to_mongo()

        # Success notification
        flash(f"{name_first} {name_last} successfully added to your contact list.", 'success')

    return render_template("contacts/new_contact.html")


@contact_blueprint.route("/edit/<string:contact_id>", methods=['GET', 'POST'])
@requires_login
def edit_contact(contact_id):
    if request.method == "POST":
        # Populate the Data
        name_first = request.form["name_first"]
        name_last = request.form["name_last"]
        phone = request.form["phone"]
        email = request.form["email"]
        address = request.form["address"]

        contact = Contact.get_by_id(contact_id)

        # Update data and save
        contact.name_first = name_first
        contact.name_last = name_last
        contact.phone = phone
        contact.email = email
        contact.address = address
        contact.save_to_mongo()

        # Future: some sort of confirmation that this worked
        return redirect(url_for('contacts.details_contact', contact_id=contact_id))

    return render_template("contacts/edit_contact.html", contact=Contact.get_by_id(contact_id))


@contact_blueprint.route("/delete/<string:contact_id>")
@requires_login
def delete_contact(contact_id):
    contact = Contact.get_by_id(contact_id)
    if contact.user_email == session['email']:
        contact.remove_from_mongo()
    return redirect(url_for(".index"))


@contact_blueprint.route("/details/<string:contact_id>")
@requires_login
def details_contact(contact_id):
    return render_template("contacts/details.html", contact=Contact.get_by_id(contact_id))

views/originals.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from models.original import Original
from flask import session
from models.user import requires_login


original_blueprint = Blueprint("originals", __name__)


@original_blueprint.route("/")
@requires_login
def index():
    originals = Original.find_many_by('user_email', session['email'])
    return render_template("originals/index.html", originals=originals)


@original_blueprint.route("/new", methods=['GET', 'POST'])
@requires_login
def new_original():
    if request.method == "POST":
        # Populate the Data
        title = request.form["title"]
        medium = request.form["medium"]
        dimensions = request.form["dimensions"]
        price = request.form["price"]
        date_created = request.form["date_created"]
        status = request.form["status"]
        possession = request.form["possession"]
        has_prints = request.form["has_prints"]
        is_commission = request.form["is_commission"]
        user_email = session['email']

        # Initialize Object and save to database
        Original(title,
                 medium,
                 dimensions,
                 price,
                 date_created,
                 status,
                 possession,
                 has_prints,
                 is_commission,
                 user_email).save_to_mongo()

        # Future: some sort of confirmation that this worked
        flash(f"{title} successfully added to your collection.", 'success')
    return render_template("originals/new_original.html")


@original_blueprint.route("/edit/<string:original_id>", methods=['GET', 'POST'])
@requires_login
def edit_original(original_id):
    if request.method == "POST":
        # Populate the Data
        title = request.form["title"]
        medium = request.form["medium"]
        dimensions = request.form["dimensions"]
        price = request.form["price"]
        date_created = request.form["date_created"]
        status = request.form["status"]
        possession = request.form["possession"]
        has_prints = request.form["has_prints"]
        is_commission = request.form["is_commission"]

        original = Original.get_by_id(original_id)

        # Update data and save
        original.title = title
        original.medium = medium
        original.dimensions = dimensions
        original.price = price
        original.date_created = date_created
        original.status = status
        original.possession = possession
        original.has_prints = has_prints
        original.is_commission = is_commission
        original.save_to_mongo()

        # Future: some sort of confirmation that this worked
        return redirect(url_for('originals.details_original', original_id=original_id))

    return render_template("originals/edit_original.html", original=Original.get_by_id(original_id))


@original_blueprint.route("/delete/<string:original_id>")
@requires_login
def delete_original(original_id):
    original = Original.get_by_id(original_id)
    if original.user_email == session['email']:
        original.remove_from_mongo()
    return redirect(url_for(".index"))


@original_blueprint.route("/details/<string:original_id>")
@requires_login
def details_original(original_id):
    return render_template("originals/details.html", original=Original.get_by_id(original_id))

views/users.py
from flask import Blueprint, request, session, url_for, render_template, redirect
from models.user import User, UserErrors

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            User.register_user(email, password)
            session['email'] = email
            return email
        except UserErrors.UserError as e:
            return e.message

    return render_template('users/register.html')


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return email
        except UserErrors.UserError as e:
            return e.message

    return render_template('users/login.html')


@user_blueprint.route('/logout')
def logout():
    session['email'] = None
    return redirect('login')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ARTrack</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
<!--Main Menu-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
      <a class="navbar-brand" href="/">ARTrack</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('originals.index') }}">Originals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('contacts.index') }}">Contacts</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login_user') }}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register_user') }}">Sign up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout')}}">Logout</a>
            </li>

        </ul>
      </div>
    </nav>

<div class="container-fluid mx3 my2">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
<div class="mt-3">
{% block content %}

{% endblock %}
</div>
</div>


<!--JS-->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>

templates/landing.html
{% extends "base.html" %}
{% block content %}

    <div class="jumbotron">
        <h1 class="display-4">All your artwork's data in one place</h1>
        <p class="lead">Use this service to track your originals, commissions, prints, contacts, and more</p>
        <hr class="my-4">
        <p>of course, none of this functionality is available yet...</p>
    </div>

{% endblock %}