models/contact.py
from dataclasses import dataclass, field
from models.model import Model
from abc import ABCMeta
import uuid
from typing import List, Dict, TypeVar, Type


@dataclass(eq=False)
class Contact(Model, metaclass=ABCMeta):
    collection: str = field(init=False, default="contacts")
    name_first: str
    name_last: str
    phone: str
    email: str
    address: str
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    # def __post_init__(self):
    #     self.name_full = self.name_first + " " + self.name_last

    def json(self) -> Dict:
        return {
            "name_first": self.name_first,
            "name_last": self.name_last,
            # "name_full": self.name_full,
            "phone": self.phone,
            "email": self.email,
            "address": self.address,
            "user_email": self.user_email,
            "_id": self._id
        }

    # @classmethod
    # def get_by_full_name(cls: "Contact", name_full: str) -> "Contact":
    #     return cls.find_one_by("name_full", name_full)

views/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from models.original import Original
from models.contact import Contact
from flask import session, flash
from models.user import requires_login

contact_blueprint = Blueprint("contacts", __name__)


@contact_blueprint.route("/")
@requires_login
def index():
    contacts = Contact.find_many_by('user_email', session['email'])
    return render_template("contacts/index.html", contacts=contacts)


@contact_blueprint.route("/new", methods=['GET', 'POST'])
@requires_login
def new_contact():
    if request.method == "POST":
        # Populate the Data
        name_first = request.form["name_first"]
        name_last = request.form["name_last"]
        phone = request.form["phone"]
        email = request.form["email"]
        address = request.form["address"]
        user_email = session['email']

        # Initialize Object and save to database
        Contact(name_first,
                name_last,
                phone,
                email,
                address,
                user_email).save_to_mongo()

        # Success notification
        flash(f"{name_first} {name_last} successfully added to your contact list.", 'success')

    return render_template("contacts/new_contact.html")


@contact_blueprint.route("/edit/<string:contact_id>", methods=['GET', 'POST'])
@requires_login
def edit_contact(contact_id):
    if request.method == "POST":
        # Populate the Data
        name_first = request.form["name_first"]
        name_last = request.form["name_last"]
        phone = request.form["phone"]
        email = request.form["email"]
        address = request.form["address"]

        contact = Contact.get_by_id(contact_id)

        # Update data and save
        contact.name_first = name_first
        contact.name_last = name_last
        contact.phone = phone
        contact.email = email
        contact.address = address
        contact.save_to_mongo()

        # Future: some sort of confirmation that this worked
        return redirect(url_for('contacts.details_contact', contact_id=contact_id))

    return render_template("contacts/edit_contact.html", contact=Contact.get_by_id(contact_id))


@contact_blueprint.route("/delete/<string:contact_id>")
@requires_login
def delete_contact(contact_id):
    contact = Contact.get_by_id(contact_id)
    if contact.user_email == session['email']:
        contact.remove_from_mongo()
    return redirect(url_for(".index"))


@contact_blueprint.route("/details/<string:contact_id>")
@requires_login
def details_contact(contact_id):
    return render_template("contacts/details.html", contact=Contact.get_by_id(contact_id))

templates/contacts/details.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1 class="my-3">{{ contact.name_first }} {{ contact.name_last }}</h1>
</header>
<section>
    <div class="shadow p-3 mb-5 bg-light rounded">
        <dl class="row">
            <dt class="col-sm-2">First Name</dt>
            <dd class="col-sm-10">{{ contact.name_first }}</dd>
            <dt class="col-sm-2">Last Name</dt>
            <dd class="col-sm-10">{{ contact.name_last }}</dd>
            <dt class="col-sm-2">Phone</dt>
            <dd class="col-sm-10">{{ contact.phone }}</dd>
            <dt class="col-sm-2">Email</dt>
            <dd class="col-sm-10">{{ contact.email }}</dd>
            <dt class="col-sm-2">Address</dt>
            <dd class="col-sm-10">{{ contact.address }}</dd>
        </dl>
        <a class="btn btn-secondary" href="{{ url_for('contacts.edit_contact', contact_id=contact._id) }}">Edit {{ contact.name_first }}</a>
    </div>
    <a class="btn btn-primary" href="{{ url_for('.index') }}">Back</a>
</section>
{% endblock %}

templates/contacts/edit_contact.html
{% extends "base.html" %}
{% block content %}
<header>
    <h1 class="my-3">Edit "{{ contact.name_first }} {{ contact.name_last }}"</h1>
</header>
<section class="new-contact-form">
        <div class="shadow p-3 mx-3 mb-4 bg-light rounded">
            <form method="post">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="name_first">First Name</label>
                        <input type="text" class="form-control" id="name_first" name="name_first" value="{{ contact.name_first }}"
                               aria-describedby="name_firstHelp">
                        <small id="name_firstHelp" class="form-text text-muted">
                            Enter the name_first of the contact
                        </small>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="name_last">Last Name</label>
                        <input type="text" class="form-control" id="name_last" name="name_last" value="{{ contact.name_last }}"
                               aria-describedby="name_lastHelp">
                        <small id="name_lastHelp" class="form-text text-muted">
                            Enter the Last Name of the contact
                        </small>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="phone">Phone</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="{{ contact.phone }}"
                               aria-describedby="phoneHelp">
                        <small id="phoneHelp" class="form-text text-muted">
                            Sample Help Text
                        </small>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email" value="{{ contact.email }}"
                               aria-describedby="emailHelp">
                        <small id="emailHelp" class="form-text text-muted">
                            Sample Help Text
                        </small>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="address">Address</label>
                        <input type="text" class="form-control" id="address" name="address" value="{{ contact.address }}"
                               aria-describedby="addressHelp">
                        <small id="addressHelp" class="form-text text-muted">
                            Sample Help Text
                        </small>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                <a class="btn btn-secondary ml-2" href="{{ url_for('.index') }}">Back</a>
            </form>
        </div>


        <!--        Generic Field-->
        <!--        <div class="form-group">-->
       <!--            <label for="sample">Field First Name</label>-->
        <!--            <input type="text" class="form-control" id="sample" name="sample" value="sample_placeholder"-->
        <!--                   aria-describedby="sampleHelp">-->
        <!--            <small id="sampleHelp" class="form-text text-muted">-->
        <!--                Sample Help Text-->
        <!--            </small>-->
        <!--        </div>-->
        <!--        End Generic Field-->
</section>
{% endblock %}

templates/contacts/index.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1 class="my-3">Contacts</h1>
</header>
<section>
    <div class="shadow p-3 mx-3 mb-4 bg-light rounded">
    <div class="list-group my-3">
        {% for contact in contacts %}
            <div class="list-group-item">
                <h4>{{ contact.name_first }} {{ contact.name_last }}</h4>
                <a href="{{ url_for('contacts.details_contact', contact_id=contact._id) }}">
                    Details
                </a>
                <a> | </a>
                <a href="{{ url_for('contacts.edit_contact', contact_id=contact._id) }}">
                    Edit
                </a>
                <a> | </a>
                <a class="text-danger" href="{{ url_for('contacts.delete_contact', contact_id=contact._id) }}">
                    Delete
                </a>
            </div>
{% endfor %}
    </div>

    <a class="btn btn-primary" href="{{ url_for('contacts.new_contact') }}">Add New</a>
    </div>
</section>
{% endblock %}

templates/contacts/new_contact.html
{% extends "base.html" %}
{% block content %}
<header>
    <h1 class="my-3">New Contact</h1>
</header>
<section class="new-original-form">


    <div class="shadow p-3 mx-3 mb-4 bg-light rounded">
        <form method="post">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="name_first">First Name</label>
                    <input type="text" class="form-control" id="name_first" name="name_first" placeholder="John Doe"
                           aria-describedby="name_firstHelp">
                    <small id="name_firstHelp" class="form-text text-muted">
                        Enter the name_first of the contact
                    </small>
                </div>

                <div class="form-group col-md-6">
                    <label for="name_last">Last Name</label>
                    <input type="text" class="form-control" id="name_last" name="name_last" placeholder="Doe"
                           aria-describedby="name_lastHelp">
                    <small id="name_lastHelp" class="form-text text-muted">
                        Enter the Last Name of the contact
                    </small>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="phone">Phone</label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="0000000000"
                           aria-describedby="phoneHelp">
                    <small id="phoneHelp" class="form-text text-muted">
                        Sample Help Text
                    </small>
                </div>

                <div class="form-group col-md-6">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email" placeholder="example@example.com"
                           aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">
                        Sample Help Text
                    </small>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" id="address" name="address"
                           placeholder="123 Example St, Nashville, TN 37212" aria-describedby="addressHelp">
                    <small id="addressHelp" class="form-text text-muted">
                        Sample Help Text
                    </small>
                </div>

            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-secondary ml-2" href="{{ url_for('.index') }}">Back</a>
        </form>
    </div>



<!--        Generic Field-->
<!--        <div class="form-group col-md-6">-->
<!--            <label for="sample">Field Title</label>-->
<!--            <input type="text" class="form-control" id="sample" name="sample" placeholder="sample_placeholder"-->
<!--                   aria-describedby="sampleHelp">-->
<!--            <small id="sampleHelp" class="form-text text-muted">-->
<!--                Sample Help Text-->
<!--            </small>-->
<!--        </div>-->
<!--        End Generic Field-->


</section>
{% endblock %}